language: cpp
dist: trusty
sudo: false

branches:
  only:
  - master
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

matrix:
  include:

  - os: linux
    env: STYLE DOCS
    cache: false
    before_install:
    - pyenv global $(pyenv whence 2to3)  # activate all python versions
    - python3 -m pip install --user --upgrade pip wheel
    install:
    - python3 -m pip install --user --upgrade sphinx sphinx_rtd_theme breathe flake8
    script:
    - flake8
    - python3 -m sphinx -W -b html docs docs/.build

  - os: linux
    python: 2.7
    compiler: gcc

  - os: linux
    python: 3.4
    compiler: clang
    env: PY=python3 CC=clang CXX=clang++

  - os: linux
    python: 3.6
    compiler: clang
    env: PY=python3 CC=clang CXX=clang++

before_install:
- pip install --user --upgrade pip virtualenv
- virtualenv -p ${PY:-python} venv
- source venv/bin/activate
- python --version
- ${CXX:-c++} --version

install:
- python setup.py sdist
- pip install --verbose dist/*.tar.gz
- rm -rf dist build

script:
- python -c 'import tensorstore; assert tensorstore.add(2, 2) == 4'
- CFLAGS='-Wall -Wextra -Wframe-larger-than=16384 -Wformat-security -Werror' python setup.py bdist_wheel

notifications:
  email: false
